# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
luau = "luau-lang/luau@0.725"
stylua = "JohnnyMorganz/StyLua@2.5.2"
